#spring.application.name=shop_cohort51
#spring.datasource.url=jdbc:postgresql://localhost:5433/g_51_shop
#spring.datasource.username=my_user
#spring.datasource.password=pos1234
#spring.datasource.driver-class-name=org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/g_51_shop
    username: my_user
    password: pos1234
    driver-class-name: org.postgresql.Driver


  application:
    name: shop_cohort51

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml